### PR TITLE
fix(php): handle serialization of OperationIndexParams in ApiWrapper

### LINKED ISSUE #759: [bug]: operationIndex() TypeError — OperationIndexParams model not serialised before array_merge
### Description

`SearchClient::operationIndex()` advertises `array|OperationIndexParams` as the type for its second argument (see the docblock for `operationIndex` in `lib/Api/SearchClient.php`), but passing an `OperationIndexParams` model object triggers a `TypeError` at runtime.

## Reproduction

```
php
use Algolia\AlgoliaSearch\Api\SearchClient;
use Algolia\AlgoliaSearch\Model\Search\OperationIndexParams;
use Algolia\AlgoliaSearch\Model\Search\OperationType;
use Algolia\AlgoliaSearch\Model\Search\ScopeType;

$client = SearchClient::create('APP_ID', 'API_KEY');

$client->operationIndex(
    'my_index',
    (new OperationIndexParams())
        ->setOperation(OperationType::COPY)
        ->setDestination('my_index_temp')
        ->setScope([ScopeType::SETTINGS, ScopeType::SYNONYMS, ScopeType::RULES])
);
```

Passing an equivalent associative array succeeds, while the model-object variant fails immediately.

## Root cause

`SearchClient::operationIndexWithHttpInfo()` (`lib/Api/SearchClient.php`, around line 3233) assigns the model directly to `$httpBody` without serialising it:

```php
$httpBody = $operationIndexParams;
```

`ApiWrapper::request()` (`lib/RetryStrategy/ApiWrapper.php`, line 151) then calls:

```php
$body = isset($data)
    ? array_merge($data, $requestOptions->getBody())
    : $data;
```

## Expected

Either:
- The model-object path is serialised before the transporter sees it, matching the docblock contract; or
- The docblock is corrected to `array` only, and the `OperationIndexParams` model is removed from the public surface of `operationIndex()`.

## Environment

- PHP 8.4.17
- `algolia/algoliasearch-client-php`: 4.41.1 (also reproduces on 4.39.1)

## Related
- Downstream fix in scout-extended: [algolia/scout-extended#367](https://github.com/algolia/scout-extended/pull/367)
- Tracking issue: [algolia/scout-extended#366](https://github.com/algolia/scout-extended/issues/366)

### Client

Search

### Version

4.41.1

### Relevant log output

```shell
TypeError: array_merge(): Argument #1 must be of type array,
Algolia\AlgoliaSearch\Model\Search\OperationIndexParams given
at vendor/algolia/algoliasearch-client-php/lib/RetryStrategy/ApiWrapper.php:151
  /vendor/algolia/algoliasearch-client-php/lib/RetryStrategy/ApiWrapper.php(102): request()
  /vendor/algolia/algoliasearch-client-php/lib/Api/SearchClient.php(4624): sendRequestWithHttpInfo()
  /vendor/algolia/algoliasearch-client-php/lib/Api/SearchClient.php(3244): operationIndexWithHttpInfo()
  /vendor/algolia/algoliasearch-client-php/lib/Api/SearchClient.php(1062): operationIndex()
  /vendor/algolia/scout-extended/src/Console/Commands/ReImportCommand.php(68): handle()
```

### PR DESCRIPTION
**Pull request by MarioAlexandruDan**
## 🧭 What and Why

SearchClient::operationIndex() advertises array|OperationIndexParams as the type for its second argument (see the docblock for operationIndex in lib/Api/SearchClient.php), but passing an OperationIndexParams model object triggers a TypeError at runtime. 
closes https://github.com/algolia/algoliasearch-client-php/issues/759

🎟 JIRA Ticket [API-407](https://algolia.atlassian.net/browse/API-407):

### Changes included:

- List changes

## 🧪 Test

[API-407]: https://algolia.atlassian.net/browse/API-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: clients/algoliasearch-client-php/lib/RetryStrategy/ApiWrapper.php [hunk 1]
```diff
@@ -147,9 +147,14 @@ private function request(
...
-            ? array_merge($data, $requestOptions->getBody())
-            : $data;
+        $requestBody = $requestOptions->getBody();
+        if ($data instanceof \JsonSerializable && !empty($requestBody)) {
+            $body = array_merge((array) $data->jsonSerialize(), $requestBody);
+        } elseif (is_array($data)) {
+            $body = array_merge($data, $requestBody);
+        } else {
+            $body = $data;
+        }
```
Comment (Fluf22) [inline clients/algoliasearch-client-php/lib/RetryStrategy/ApiWrapper.php]:
```suggestion
        if ($data instanceof \JsonSerializable) {
            $data = (array) $data->jsonSerialize();
        }

        $body = isset($data)
            ? array_merge($data, $requestOptions->getBody())
            : $data;
```

**Review by Fluf22 — COMMENTED** [review]
Last comment, I think we can simplify

**Review by Fluf22 — APPROVED** [review]
